server {
    listen 80;
    listen [::]:80;
    server_name YOUR_DOMAIN;

    root /var/www/medication-checkin/current;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
